### PR TITLE
IGA - token list add

### PR DESCRIPTION
**Pull request by doncandy**
IGA irc token list add.

### CODE REVIEW

**Comment by Spl3en** [comment]
@doncandy Out of curiosity, is IGA related to "ICXGames" ? 
https://tracker.icon.foundation/transaction/0xde7dfeb05ddcceec7194042a8a635c9847295cdfcff015b9b9c8bcda92f0ac32

**Comment by doncandy** [comment]
> @doncandy Out of curiosity, is IGA related to "ICXGames" ?
> https://tracker.icon.foundation/transaction/0xde7dfeb05ddcceec7194042a8a635c9847295cdfcff015b9b9c8bcda92f0ac32

@Spl3en 
yes. I'm ICXGames developer member. IGA is reward token of ICXGames.

**Comment by Spl3en** [comment]
@doncandy May I know if you're hosting a DApp somewhere on Internet, and if so can you share a link ? I can see a lot of transactions on the ICON Blockchain related to ICXGames.

**Comment by doncandy** [comment]
@Spl3en 
We are preparing icxgames service, you can see fantastic service soon, plz wait

**Comment by jeongsang-y** [comment]
@doncandy IGA added to the "Add token" list

**Pull request closed without merging**
